//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CApp.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailNotification
    {
        public System.Guid EmailNotificationID { get; set; }
        public System.Guid UserID { get; set; }
        public string EmailBodyPlain { get; set; }
        public string EmailBodyHTML { get; set; }
        public string EmailSubjectHTML { get; set; }
        public string EmailSubjectPlain { get; set; }
        public int EmailStatus { get; set; }
        public string From { get; set; }
        public string TO { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
        public string FailureMessage { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
