//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CApp.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorReport
    {
        public System.Guid ErrorReportID { get; set; }
        public string ErrorSource { get; set; }
        public string IPAddress { get; set; }
        public string Description { get; set; }
        public System.Guid UserID { get; set; }
        public string RequestData { get; set; }
        public string StackTrace { get; set; }
        public string ErrorCode { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
