//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CApp.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public System.Guid UserSettingID { get; set; }
        public System.Guid SettingID { get; set; }
        public System.Guid UserID { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<int> IntValue { get; set; }
        public string StringValue { get; set; }
        public int MinRange { get; set; }
        public long MaxRange { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
