//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CApp.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPost
    {
        public System.Guid UserPostID { get; set; }
        public string PostSubject { get; set; }
        public string PostContent { get; set; }
        public Nullable<System.Guid> UserFileID { get; set; }
        public System.Guid UserID { get; set; }
        public bool IsTrustedPost { get; set; }
        public System.Guid PostTypeID { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
